# Setup PHP as Language to Use
language: php

# Choose the PHP Version to test
php:
  - '5.5'
  - '5.6'
  - '7.0'
  - '7.1'

matrix:
  allow_failures:
    - php: 5.5

# Initialization
before_script:
  - composer self-update
  - composer install --no-interaction

# Script Execution
script: 
  - mkdir -p tests/code-coverage
  - ./vendor/bin/phpunit

after_success:
  - travis_retry php vendor/bin/coveralls -v
