# Setup PHP as Language to Use
language: php

# Choose the PHP Version to test
php:
  - '5.5'
  - '5.6'
  - '7.0'
  - '7.1'

# Initialization
before_script:
  - composer self-update
  - composer install

# Script Execution
script: ./vendor/bin/phpunit